<?php
$defaults = array();

$defaults['add_new']['en']			= 'Add New';
$defaults['add_new']['es']			= 'Agregar nuevo';
$defaults['add_new']['fr']			= 'Ajouter un nouveau';
$defaults['add_new']['ru']			= 'Добавить';

$defaults['administrative_info']['en']	= 'Administrative Information';
$defaults['administrative_info']['es']	= 'Información Administrativa';
$defaults['administrative_info']['fr']	= 'Renseignements administratifs';
$defaults['administrative_info']['ru']	= 'Административная информация';

$defaults['app_name']['en']			= 'Intranet';

$defaults['app_welcome']['en']		= 'Welcome to the Intranet.  If you don\'t have a login for this site or if you are having trouble, please use the links below:';

$defaults['are_you_sure']['en']		= 'Are you sure?';
$defaults['are_you_sure']['es']		= '¿Estás seguro?';
//$defaults['are_you_sure']['fr']		= 'Bio';
//$defaults['are_you_sure']['ru']		= 'Биография';

$defaults['bio']['en']		= 'Bio';
$defaults['bio']['es']		= 'Bio';
$defaults['bio']['fr']		= 'Bio';
$defaults['bio']['ru']		= 'Биография';

$defaults['category']['en']			= 'Category';
$defaults['category']['es']			= 'Categoría';
$defaults['category']['fr']			= 'Catégorie';
$defaults['category']['ru']			= 'Категории';

$defaults['categories']['en']			= 'Categories';
$defaults['categories']['es']			= 'Categorías';
$defaults['categories']['fr']			= 'Catégories';
$defaults['categories']['ru']			= 'Категория';

$defaults['clips']['en']			= 'Clips';
$defaults['clips']['es']			= 'Clips';
$defaults['clips']['fr']			= 'Clips';
$defaults['clips']['ru']			= 'Клипы';

$defaults['date']['en']		= 'Date';
$defaults['date']['es']		= 'Fecha';
$defaults['date']['fr']		= 'Date';
$defaults['date']['ru']		= 'Свидание';

$defaults['delete']['en']		= 'Delete';
$defaults['delete']['es']		= 'Borrar';
$defaults['delete']['fr']		= 'Supprimer';
$defaults['delete']['ru']		= 'Удалить';

$defaults['description']['en']		= 'Description';
$defaults['description']['es']		= 'Descripción';
$defaults['description']['fr']		= 'Description';
$defaults['description']['ru']		= 'Описание';

$defaults['documents_empty']['en']		= 'No documents added yet';
$defaults['documents_empty']['es']		= 'No hay documentos que agregó aún';
$defaults['documents_empty']['fr']		= 'Aucun document n\'a pas encore ajouté';
$defaults['documents_empty']['ru']		= 'Никаких документов добавили еще';

$defaults['docs_recent_views']['en']	= 'Recent Views';
$defaults['docs_recent_views']['es']	= 'Visitas recientes';
$defaults['docs_recent_views']['fr']	= 'Affichages récents';
$defaults['docs_recent_views']['ru']	= 'Последние окна';

$defaults['downloads']['en']	= 'Downloads';
$defaults['downloads']['es']	= 'Descargas';
$defaults['downloads']['fr']	= 'Téléchargements';
$defaults['downloads']['ru']	= 'Загрузки';

$defaults['edit']['en']		= 'Edit';
$defaults['edit']['es']		= 'Modificar';
$defaults['edit']['fr']		= 'Modifier';
$defaults['edit']['ru']		= 'Изменить';

$defaults['email']['en']		= 'Email';
$defaults['email']['es']		= 'Email';
$defaults['email']['fr']		= 'Email';
$defaults['email']['ru']		= 'Электронная почта';

$defaults['end_date']['en']		= 'End Date';
$defaults['end_date']['es']		= 'Fecha de finalización';
$defaults['end_date']['fr']		= 'Date de fin';
$defaults['end_date']['ru']		= 'Дата окончания';

$defaults['email_footer']['en']		= 'This message was generated by the ';

$defaults['events_empty']['en']		= 'No upcoming events';
$defaults['events_empty']['es']		= 'No hay próximos eventos';
$defaults['events_empty']['fr']		= 'Aucun événement à venir';
$defaults['events_empty']['ru']		= 'Нет предстоящих событий';

$defaults['file']['en']		= 'File';
$defaults['file']['es']		= 'Archivo';
$defaults['file']['fr']		= 'Fichier';
$defaults['file']['ru']		= 'Файл';

$defaults['hello']['en']		= 'Hello';
$defaults['hello']['es']		= 'Hola';
$defaults['hello']['fr']		= 'Bonjour';
$defaults['hello']['ru']		= 'Привет';

$defaults['help_hide']['en']	= 'Hide Help';
$defaults['help_hide']['es']	= 'Ayuda Ocultar';
$defaults['help_hide']['fr']	= 'Masquer l\'aide';
$defaults['help_hide']['ru']	= 'помощь мостовья';

$defaults['help_show']['en']	= 'Show Help';
$defaults['help_show']['es']	= 'Mostrar Ayuda';
$defaults['help_show']['fr']	= 'Afficher l\'aide';
$defaults['help_show']['ru']	= 'Показать помощь';

$defaults['home']['en']	= 'Home';
$defaults['home']['es']	= 'Inicio';
$defaults['home']['fr']	= 'Accueil';
$defaults['home']['ru']	= 'Дом';

$defaults['is_admin']['en']			= 'Is Admin';
$defaults['is_admin']['es']			= 'Es administrativo';
$defaults['is_admin']['fr']			= 'Est administratif';
$defaults['is_admin']['ru']			= 'административно';

$defaults['jump_to']['en']			= 'Jump To';
$defaults['jump_to']['es']			= 'Salte a';
$defaults['jump_to']['fr']			= 'Sautez à';
$defaults['jump_to']['ru']			= 'поскачите к';

$defaults['language']['en']			= 'Language';
$defaults['language']['es']			= 'Idioma';
$defaults['language']['fr']			= 'Langue';
$defaults['language']['ru']			= 'Язык';

$defaults['last_login']['en']			= 'Last Login';
$defaults['last_login']['es']			= 'Último inicio de sesión';
$defaults['last_login']['fr']			= 'Dernière connexion';
$defaults['last_login']['ru']			= 'Последние Логин';

$defaults['last_post']['en']			= 'Last Post';
$defaults['last_post']['es']			= 'Último';
$defaults['last_post']['fr']			= 'Dernier';
$defaults['last_post']['ru']			= 'Последнее сообщение';

$defaults['link']['en']		= 'Link';
$defaults['link']['es']		= 'Vínculo';
$defaults['link']['fr']		= 'Lien';
$defaults['link']['ru']		= 'Ссылка';

$defaults['links_edit']['en']		= 'Edit Links';
$defaults['links_edit']['es']		= 'Modificar vínculos';
$defaults['links_edit']['fr']		= 'Modifier les liens';
$defaults['links_edit']['ru']		= 'Изменить ссылку';

$defaults['log_out']['en']		= 'Log Out';
$defaults['log_out']['es']		= 'Cierre de sesión';
$defaults['log_out']['fr']		= 'Déconnexion';
$defaults['log_out']['ru']		= 'Выйти';

$defaults['login_account_request']['en'] = 'Request an Account';

$defaults['login_password_reset_msg']['en'] = '<h1>Starting Over, Password-Wise</h1>Your old password can\'t be recovered, since it was encrypted.  However, it can be reset so you can pick a new one.  What is the email address on the account?';

$defaults['login_password_reset_msg_email_not_found']['en'] = '<h1>Email Not Found</h1>That email address wasn\'t found in the system.  If the address below is correct and you\'ve never logged in, you may need to <a href="account_request.php">request an account</a>.';

$defaults['name']['en']			= 'Name';
$defaults['name']['es']			= 'Nombre';
$defaults['name']['fr']			= 'Nom';
$defaults['name']['ru']			= 'Имя';

$defaults['network']['en']			= 'Network';
$defaults['network']['es']			= 'Red';
$defaults['network']['fr']			= 'Réseau';
$defaults['network']['ru']			= 'Сеть';

$defaults['networks']['en']			= 'Networks';
$defaults['networks']['es']			= 'Redes';
$defaults['networks']['fr']			= 'Réseaux';
$defaults['networks']['ru']			= 'Сети';

$defaults['networks_view_all']['en']			= 'View All Networks';
$defaults['networks_view_all']['es']			= 'Ver todos los videos';
$defaults['networks_view_all']['fr']			= 'Tout voir';
$defaults['networks_view_all']['ru']			= 'Открыть Все сети';

$defaults['organization']['en']			= 'Organization';
$defaults['organization']['es']			= 'Organización';
$defaults['organization']['fr']			= 'Organisation';
$defaults['organization']['ru']			= 'Организация';

$defaults['page_edit_info']['en']	= 'Edit Page Info';
$defaults['page_edit_info']['es']	= 'Información de la página';
$defaults['page_edit_info']['fr']	= 'Modifier une page info';
$defaults['page_edit_info']['ru']	= 'Редактировать страницу информация';

$defaults['password']['en'] = 'Password';
$defaults['password']['es'] = 'Contraseña';
$defaults['password']['fr'] = 'Mot de passe';
//$defaults['password']['ru'] = 'Reset Password';

$defaults['password_is_reset']['en'] = 'Password is Reset';
//$defaults['password_reset']['es'] = 'Reset Password';
//$defaults['password_reset']['fr'] = 'Reset Password';
//$defaults['password_reset']['ru'] = 'Reset Password';

$defaults['password_reset']['en'] = 'Reset Password';
$defaults['password_reset']['es'] = 'Restablecer Contraseña';
$defaults['password_reset']['fr'] = 'Remettez le mot de passe';
//$defaults['password_reset']['ru'] = 'Reset Password';

$defaults['posted_by']['en']			= 'Posted By';
$defaults['posted_by']['es']			= 'Publicado por';
$defaults['posted_by']['fr']			= 'Signalé près';
$defaults['posted_by']['ru']			= 'вывешено мимо';

$defaults['pressclips_recent_empty']['en'] = 'There are no recent clips.';
$defaults['pressclips_recent_empty']['es'] = 'No hay clips recientes.';
$defaults['pressclips_recent_empty']['fr'] = 'Il n\'y a pas de clips récents.';
$defaults['pressclips_recent_empty']['ru'] = 'Есть не последних клипов.';

$defaults['published']['en']			= 'Published';
$defaults['published']['es']			= 'Publicado';
$defaults['published']['fr']			= 'Publié';
$defaults['published']['ru']			= 'Опубликован';

$defaults['publication']['en']			= 'Publication';
$defaults['publication']['es']			= 'Publicación';
$defaults['publication']['fr']			= 'Publication';
$defaults['publication']['ru']			= 'Публикация';

$defaults['replies']['en']			= 'Replies';
$defaults['replies']['es']			= 'Respuestas';
$defaults['replies']['fr']			= 'Réponses';
$defaults['replies']['ru']			= 'Ответы';

$defaults['staff_firsttime']['en']	= 'Welcome to the Intranet!  Since this is your first time logging in, please make certain that your information here is correct, then click \'save changes\' at the bottom.';

$defaults['staff_new']['en']	= 'Recent Arrivals';
$defaults['staff_new']['es']	= 'Los recién llegados';
//$defaults['staff_new']['fr']	= 'Recent Arrivals';
$defaults['staff_new']['ru']	= 'Новоприбывших';

$defaults['staff_new_empty']['en']	= 'No staff are listed as having started in the last two months.';
$defaults['staff_new_empty']['es']	= 'Ningún miembro del personal se muestran como se inició en los últimos dos meses.';
$defaults['staff_new_empty']['fr']	= 'Aucun membre du personnel sont répertoriés comme ayant commencé au cours des deux derniers mois.';
$defaults['staff_new_empty']['ru']	= 'Нет персонала указаны как, начавшийся в последние два месяца.';


$defaults['staff_update']['en']		= 'Your personal info hasn\'t been updated in a while.  Please update this form and click Save at the bottom.  Your home and emergency contact information will remain private -- only senior staff will have access to it.';

$defaults['start_date']['en']			= 'Start Date';
$defaults['start_date']['es']			= 'Fecha de inicio';
$defaults['start_date']['fr']			= 'Date de début';
$defaults['start_date']['ru']			= 'Дата начала';

$defaults['starter']['en']			= 'Started By';
$defaults['starter']['es']			= 'Iniciado por';
$defaults['starter']['fr']			= 'Commencé par';
$defaults['starter']['ru']			= 'К работе';

$defaults['staff_empty']['en']		= 'No staff match those criteria.';
$defaults['staff_empty']['es']		= 'Ningún miembro del personal coinciden con los criterios.';
$defaults['staff_empty']['fr']		= 'Aucun membre du personnel correspondant à ces critères.';
$defaults['staff_empty']['ru']		= 'Нет персонала соответствуют этим критериям.';

$defaults['staff_search']['en']			= 'Search Staff';
$defaults['staff_search']['es']			= 'Búsqueda de personal';
$defaults['staff_search']['fr']			= 'Recherche personnel';
$defaults['staff_search']['ru']			= 'Поиск персонала';

$defaults['staff_title']['en']			= 'Job Title';
$defaults['staff_title']['es']			= 'Título del Empleo';
$defaults['staff_title']['fr']			= 'Titre de l\'emploi';
$defaults['staff_title']['ru']			= 'Должность';

$defaults['telephone']['en']			= 'Telephone';
$defaults['telephone']['es']			= 'Teléfono';
$defaults['telephone']['fr']			= 'Téléphone';
$defaults['telephone']['ru']			= 'Телефон';

$defaults['title']['en']			= 'Title';
$defaults['title']['es']			= 'Título';
$defaults['title']['fr']			= 'Titre';
$defaults['title']['ru']			= 'Название';

$defaults['topic']['en']			= 'Topic';
$defaults['topic']['es']			= 'Tema';
$defaults['topic']['fr']			= 'Sujet';
$defaults['topic']['ru']			= 'Рубрики';

$defaults['topics']['en']			= 'Topics';
$defaults['topics']['es']			= 'Temas';
$defaults['topics']['fr']			= 'Thèmes';
$defaults['topics']['ru']			= 'Тем';

$defaults['topic_new']['en']			= 'Contribute a New Topic';
$defaults['topic_new']['es']			= 'Contribuir con un nuevo tema';
$defaults['topic_new']['fr']			= 'Contribuer par un nouveau thème';
$defaults['topic_new']['ru']			= 'Добавить новую тему';

$defaults['topics_empty']['en']			= 'No topics have been added yet.  Why not <a href="#bottom">be the first</a>?';
$defaults['topics_empty']['es']			= 'No hay temas se han añadido todavía. ¿Por qué no <a href="#bottom">no ser el primero</a>?';
$defaults['topics_empty']['fr']			= 'Aucun sujet n\'a encore été enregistré. Pourquoi <a href="#bottom">être pas le premier</a>?';
$defaults['topics_empty']['ru']			= 'Нет тем еще не было добавлено. Почему бы не <a href="#bottom">не быть первой</a>?';

$defaults['topic_admin']['en']			= 'This is an administrative announcement topic.  For more information, please contact the topic poster.';
$defaults['topic_admin']['es']			= 'Este es un tema anuncio administrativos. Para obtener más información, póngase en contacto con el anunciante tema.';
$defaults['topic_admin']['fr']			= 'C\'est un sujet annonce administratives. Pour de plus amples renseignements, s\'il vous plaît contacter l\'affiche sujet.';
$defaults['topic_admin']['ru']			= 'Это административная тема объявления. За дополнительной информацией просьба обращаться к тем авторам.';

$defaults['translations_do']['en']	= 'Do Translations';
$defaults['translations_do']['es']	= 'Haga las traducciones';
$defaults['translations_do']['fr']	= 'Faire des traductions';
$defaults['translations_do']['ru']	= 'Делают переводы';

$defaults['type']['en']	= 'Type';
$defaults['type']['es']	= 'Tipo';
$defaults['type']['fr']	= 'Type';
$defaults['type']['ru']	= 'Печатать';

$defaults['updated']['en']			= 'Updated';
$defaults['updated']['es']			= 'Actualizado';
$defaults['updated']['fr']			= 'Mise à jour';
$defaults['updated']['ru']			= 'Обновлено';

$defaults['url']['en']			= 'URL';
$defaults['url']['es']			= 'URL';
$defaults['url']['fr']			= 'URL	';
$defaults['url']['ru']			= 'URL';

$defaults['upload_max']['en']			= 'The maximum size is ';
$defaults['upload_max']['es']			= 'El tamaño máximo es ';
$defaults['upload_max']['fr']			= 'La taille maximale est ';
$defaults['upload_max']['ru']			= 'Максимальный размер ';

?>